Description: ACLs and security groups
Resources:
  PublicACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: !ImportValue "MondayHealthVPC-VPCID"
      Tags:
      - Key: Name
        Value: "Public Subnet ACL"
  PublicACLAllowHTTPOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "100"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "80"
        To: "80"
  PublicACLAllowHTTPSOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "110"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "443"
        To: "443"
  PublicACLEphemeralOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "200"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "1024"
        To: "65535"
  PublicACLAllowSSHOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "250"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 10.0.0.0/8
      PortRange:
        From: "22"
        To: "22"
  PublicACLAllowHTTPIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "100"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "80"
        To: "80"
  PublicACLAllowHTTPSIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "110"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "443"
        To: "443"
  PublicACLAllowSSHIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "150"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 10.0.0.0/8
      PortRange:
        From: "22"
        To: "22"
  PublicACLEphemeralIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PublicACL
      RuleNumber: "200"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "1024"
        To: "65535"
  PrivateACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: !ImportValue "MondayHealthVPC-VPCID"
      Tags:
      - Key: Name
        Value: "Private Subnet ACL"
  PrivateACLEphemeralIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "100"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "1024"
        To: "65535"
  PrivateACLEphemeralOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "100"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "1024"
        To: "65535"
  PrivateACLWebIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "200"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "80"
        To: "80"
  PrivateACLWebOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "200"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "80"
        To: "80"
  PrivateACLTLSIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "300"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "443"
        To: "443"
  PrivateACLTLSOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "300"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "443"
        To: "443"
  PrivateACLSSHIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "400"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "22"
        To: "22"
  PrivateACLSSHOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref PrivateACL
      RuleNumber: "400"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "22"
        To: "22"
  DMZACL:
    Type: "AWS::EC2::NetworkAcl"
    Properties:
      VpcId: !ImportValue "MondayHealthVPC-VPCID"
      Tags:
      - Key: Name
        Value: "DMZ Subnet ACL"
  DMZAllowSSHIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref DMZACL
      RuleNumber: "100"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "22"
        To: "22"
  DMZAllowEphemeralIn:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref DMZACL
      RuleNumber: "200"
      Protocol: "6"
      RuleAction: allow
      Egress: "false"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "1024"
        To: "65535"
  DMZAllowSSHOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref DMZACL
      RuleNumber: "100"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 10.0.0.0/8
      PortRange:
        From: "22"
        To: "22"
  DMZAllowEphemeralOut:
    Type: "AWS::EC2::NetworkAclEntry"
    Properties:
      NetworkAclId: !Ref DMZACL
      RuleNumber: "200"
      Protocol: "6"
      RuleAction: allow
      Egress: "true"
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: "1024"
        To: "65535"
  PublicACLAssociationA:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-PublicSubnetA"
      NetworkAclId: !Ref PublicACL
  PublicACLAssociationB:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-PublicSubnetB"
      NetworkAclId: !Ref PublicACL
  PublicACLAssociationC:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-PublicSubnetC"
      NetworkAclId: !Ref PublicACL
  PrivateACLAssociationA:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-PrivateSubnetA"
      NetworkAclId: !Ref PrivateACL
  PrivateACLAssociationB:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-PrivateSubnetB"
      NetworkAclId: !Ref PrivateACL
  PrivateACLAssociationC:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-PrivateSubnetC"
      NetworkAclId: !Ref PrivateACL
  DMZACLAssociation:
    Type: "AWS::EC2::SubnetNetworkAclAssociation"
    Properties:
      SubnetId: !ImportValue "MondayHealthVPC-DMZSubnet"
      NetworkAclId: !Ref DMZACL
